### ISSUE TITLE
你这jar包到底是怎么产生8099端口的

### ISSUE THREAD

**Issue by wangyancun** [kukume/unicom#3]

**Comment by kukume** [comment]
内嵌式tomcat

**Comment by wangyancun** [comment]
我大概清楚了，但是这个端口，没明白，是JAVA产生的，还是tomcat产生的，日志能看吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kuku"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 下午4:53
收件人:&nbsp;"kukume/unicom"<unicom@noreply.github.com&gt;;
抄送:&nbsp;"　　　　　　　　"<1504068285@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kukume/unicom] 你这jar包到底是怎么产生8099端口的 (#3)




内嵌式tomcat

**Comment by kukume** [comment]
![](https://img.kuku.me/kuku/TOIMGb77610222100225N.png)
启动的时候显示了tomcat的端口为8099。

**Comment by wangyancun** [comment]
日志从哪看呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kuku"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 下午5:04
收件人:&nbsp;"kukume/unicom"<unicom@noreply.github.com&gt;;
抄送:&nbsp;"　　　　　　　　"<1504068285@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kukume/unicom] 你这jar包到底是怎么产生8099端口的 (#3)





 启动的时候显示了tomcat的端口为8099。

**Comment by kukume** [comment]
你是通过`screen -dmS unicom...`启动的把
运行`screen -R unicom`就行了

**Comment by wangyancun** [comment]
数字识别是通过什么实现的，我看也没用百度AI
---原始邮件---
发件人:"kuku"<notifications@github.com>
发送时间:2020年2月22日 星期六 下午5:6
收件人:"kukume/unicom"<unicom@noreply.github.com>
抄送:"wangyancun"<1504068285@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [kukume/unicom] 你这jar包到底是怎么产生8099端口的 (#3)

你是通过screen -dmS unicom...启动的把
运行screen -R unicom就行了

&mdash;

**Comment by kukume** [comment]
用的tesseract-ocr，
参考的这个大佬的![https://github.com/teenyda/qingdao](https://github.com/teenyda/qingdao)

**Comment by wangyancun** [comment]
可以兄弟
